<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>RequestBench.AspNetMvc</RootNamespace>
    <AssemblyName>RequestBench.AspNetMvc</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../_shared/RequestBench.Domain.csproj" />
    <ProjectReference Include="../_hosts/RequestBench.Hosts.csproj" />
  </ItemGroup>
</Project>
