<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>RequestBench.CarterTarget</RootNamespace>
    <AssemblyName>RequestBench.Carter</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../_shared/RequestBench.Domain.csproj" />
    <ProjectReference Include="../_hosts/RequestBench.Hosts.csproj" />
    <PackageReference Include="Carter" />
    <PackageReference Include="FluentValidation" />
  </ItemGroup>
</Project>
